name: dart_phonetics
description: A collection of phonetic algorithms. These algorithms help find words or names that sound similar by generating an encoding that can be compared or indexed for fuzzy searching.
version: 0.1.0
homepage: https://github.com/raycardillo/dart_phonetics
repository: https://github.com/raycardillo/dart_phonetics

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  charcode: ^1.1.2

dev_dependencies:
  test: ^1.9.4
  pedantic: ^1.8.0+1
